const $=id=>document.getElementById(id),bridge=window.AstrBotPluginPage;let state=null,original=null,templates={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notice(t,error=false){$('notice').textContent=t;$('notice').className='notice'+(error?' error':'');$('notice').hidden=!t}
function options(selected){return state.profiles.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)}（${esc(p.id)}）</option>`).join('')}
function render(){ $('profile-count').textContent=state.profiles.length;$('route-count').textContent=state.routes.length;$('node-count').textContent=state.nodes.length;$('event-count').textContent=state.events.length;
 $('profiles').innerHTML=state.profiles.map((p,i)=>`<div class="row" data-i="${i}"><input data-k="name" value="${esc(p.name)}"><span class="kind">${esc(p.kind)}</span><input data-k="endpoint" placeholder="代理入口" value="${esc(p.endpoint||'')}"><label><input type="checkbox" data-k="enabled" ${p.enabled?'checked':''}> 启用</label><button data-delete="profile">删除</button></div>`).join('');
 $('routes').innerHTML=state.routes.map((r,i)=>`<div class="row route" data-i="${i}"><input data-k="host" value="${esc(r.host)}"><select data-k="match"><option value="exact" ${r.match==='exact'?'selected':''}>精确</option><option value="suffix" ${r.match==='suffix'?'selected':''}>后缀</option></select><select data-k="profile_id">${options(r.profile_id)}</select><label><input type="checkbox" data-k="enabled" ${r.enabled?'checked':''}> 启用</label><button data-delete="route">删除</button></div>`).join('')||'<p class="muted">暂无分流规则，所有域名默认直连。</p>';
 $('templates').innerHTML=Object.entries(templates).map(([id,t])=>`<button data-template="${id}">${esc(t.name)}<small>${esc(t.hosts.join('、'))}</small></button>`).join('');$('probe-profile').innerHTML=options('direct');
 $('events').innerHTML=state.events.slice().reverse().map(e=>`<div class="event"><span>${esc(e.action)} · ${esc(e.profile_id||e.result||'')}</span><span>${new Date((e.at||0)*1000).toLocaleString()}</span></div>`).join('')||'<p class="muted">暂无事件</p>';
 document.querySelectorAll('.row[data-i] [data-k]').forEach(el=>el.onchange=()=>{const row=el.closest('.row'),list=row.classList.contains('route')?state.routes:state.profiles,item=list[row.dataset.i];item[el.dataset.k]=el.type==='checkbox'?el.checked:el.value});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const list=b.dataset.delete==='route'?state.routes:state.profiles,row=b.closest('.row'),i=row.dataset.i;if(b.dataset.delete==='profile'&&state.profiles[i].id==='direct')return notice('直连策略不能删除',true);list.splice(i,1);render()});document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>{const t=templates[b.dataset.template],id=b.dataset.template+'-'+Date.now();state.profiles.push({id:id,name:t.name,kind:'mihomo',endpoint:'',enabled:true,fail_closed:true});t.hosts.forEach(host=>state.routes.push({host,profile_id:id,match:'exact',enabled:true}));render();notice(`${t.name} 模板已添加，请填写代理入口后再保存`)})}
 async function load(){try{state=await bridge.apiGet('state');original=structuredClone(state);templates=(await bridge.apiGet('templates')).templates;render();notice('')}catch(e){notice(e.message,true)}}
 $('add-profile').onclick=()=>{let n=1;while(state.profiles.some(p=>p.id==='profile-'+n))n++;state.profiles.push({id:'profile-'+n,name:'新策略',kind:'http',endpoint:'',enabled:true,fail_closed:true});render()};$('add-route').onclick=()=>{state.routes.push({host:'example.com',profile_id:'direct',match:'exact',enabled:true});render()};
 $('preview').onclick=async()=>{try{$('preview-result').textContent=JSON.stringify(await bridge.apiPost('preview',{host:$('host').value}),null,2)}catch(e){$('preview-result').textContent=e.message}};
 $('save').onclick=()=>{$('diff-text').textContent=JSON.stringify({before:original,after:state},null,2);$('diff').showModal()};$('diff-cancel').onclick=()=>$('diff').close();$('diff-confirm').onclick=async()=>{try{state=await bridge.apiPost('save',state);original=structuredClone(state);$('diff').close();render();notice('配置已保存')}catch(e){notice(e.message,true)}};
 $('probe').onclick=async()=>{try{$('probe').disabled=true;$('probe-result').textContent='检测中…';$('probe-result').textContent=JSON.stringify(await bridge.apiPost('probe',{profile_id:$('probe-profile').value,url:$('probe-url').value}),null,2);await load()}catch(e){$('probe-result').textContent=e.message}finally{$('probe').disabled=false}};$('reload').onclick=load;load();
